# Generated by Django 4.1.3 on 2023-06-24 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Fruit name should contain only letters!')])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrients', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
